branch-defaults:
  development:
    environment: nodenikApi-private-dev
global: 
  application_name: nodenik-api
  default_ec2_keyname: new-wordnik-key2
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: us-west-1
  profile: EB-deployer
  sc: git